apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  name: sdnr
  namespace: smo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sdnr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sdnr
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: sdnr-configmap
        image: cpqd-sdnr:latest
        imagePullPolicy: IfNotPresent
        name: sdnr
        ports:
        - containerPort: 8101
          protocol: TCP
        - containerPort: 8181
          protocol: TCP
        - containerPort: 6666
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/opendaylight/current/certs/certs.properties
          name: certprop
        - mountPath: /opt/opendaylight/current/certs/keys0.zip
          name: keyszip
        - mountPath: /opt/opendaylight/etc/mountpoint-registrar.properties
          name: mountpointregistrar
          subPath: mountpoint-registrar.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: certprop
        name: certprop
      - configMap:
          defaultMode: 420
          name: keyszip
        name: keyszip
      - configMap:
          defaultMode: 420
          name: mountpointregistrar
        name: mountpointregistrar
  replicas: 1
