apiVersion: v1
kind: Service
metadata:
  labels:
    app: sdnr
  name: sdnr
  namespace: smo
spec:
  clusterIP: 10.96.0.108
  clusterIPs:
  - 10.96.0.108
  externalIPs:
  - 192.168.122.87
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port1
    nodePort: 30101
    port: 8101
    protocol: TCP
    targetPort: 8101
  - name: port2
    nodePort: 30181
    port: 8181
    protocol: TCP
    targetPort: 8181
  - name: port3
    nodePort: 30666
    port: 6666
    protocol: TCP
    targetPort: 6666
  - name: port4
    nodePort: 30443
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: sdnr
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}