apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dmaap
  name: dmaap
  namespace: smo
spec:
  clusterIP: 10.96.0.134
  clusterIPs:
  - 10.96.0.134
  externalIPs:
  - 192.168.122.84
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "3904"
    nodePort: 32392
    port: 3904
    protocol: TCP
    targetPort: 3904
  - name: "3905"
    nodePort: 30768
    port: 3905
    protocol: TCP
    targetPort: 3905
  selector:
    io.kompose.service: dmaap
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}