apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    io.kompose.service: dmaap
  name: dmaap
  namespace: smo
  ownerReferences:
  - apiVersion: v2
    blockOwnerDeletion: true
    controller: true
    kind: Installer
    name: default
    uid: 8409d5f8-f535-4256-bd23-4e11d0a9d1eb
  resourceVersion: "3900"
  uid: 6740e8f8-7997-40e9-ab04-312bcd158878
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: dmaap
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/nonrtric-docker-net: "true"
        io.kompose.service: dmaap
    spec:
      containers:
      - env:
        - name: enableCadi
          value: "false"
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
        - name: LANG
          value: C.UTF-8
        - name: JAVA_HOME
          value: /usr/lib/jvm/java-1.8-openjdk
        - name: JAVA_VERSION
          value: 8u212
        - name: JAVA_ALPINE_VERSION
          value: 8.212.04-r0
        image: nexus3.onap.org:10001/onap/dmaap/dmaap-mr:1.1.18
        imagePullPolicy: IfNotPresent
        name: dmaap-mr
        ports:
        - containerPort: 3904
          protocol: TCP
        - containerPort: 3905
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /appl/dmaapMR1/bundleconfig/etc/appprops/MsgRtrApi.properties
          name: dmaap-claim0
          subPath: MsgRtrApi.properties
        - mountPath: /appl/dmaapMR1/bundleconfig/etc/logback.xml
          name: dmaap-claim1
          subPath: logback.xml
        - mountPath: /appl/dmaapMR1/etc/cadi.properties
          name: dmaap-claim2
          subPath: cadi.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - configMap:
          defaultMode: 420
          name: mr-api
        name: dmaap-claim0
      - configMap:
          defaultMode: 420
          name: mr-log
        name: dmaap-claim1
      - configMap:
          defaultMode: 420
          name: mr-cadi
        name: dmaap-claim2
  replicas: 1