apiVersion: v1
data:
  logback.xml: "<!--\n    ============LICENSE_START=======================================================\n
    \   Copyright © 2020 Nordix Foundation. All rights reserved.\n    Copyright ©
    2019 AT&T Intellectual Property. All rights reserved.\n    ================================================================================\n
    \   Licensed under the Apache License, Version 2.0 (the \"License\");\n    you
    may not use this file except in compliance with the License.\n    You may obtain
    a copy of the License at\n          http://www.apache.org/licenses/LICENSE-2.0\n\n
    \   Unless required by applicable law or agreed to in writing, software\n    distributed
    under the License is distributed on an \"AS IS\" BASIS,\n    WITHOUT WARRANTIES
    OR CONDITIONS OF ANY KIND, either express or implied.\n    See the License for
    the specific language governing permissions and\n    limitations under the License.\n
    \   ============LICENSE_END=========================================================\n-->\n\n<configuration
    scan=\"true\" scanPeriod=\"3 seconds\" debug=\"false\">\n  <contextName>${module.ajsc.namespace.name}</contextName>\n
    \ <jmxConfigurator />\n  <property name=\"logDirectory\" value=\"${AJSC_HOME}/log\"
    />\n  <appender name=\"STDOUT\" class=\"ch.qos.logback.core.ConsoleAppender\">\n
    \   <filter class=\"ch.qos.logback.classic.filter.LevelFilter\">\n      <level>ERROR</level>\n
    \     <onMatch>ACCEPT</onMatch>\n      <onMismatch>DENY</onMismatch>\n    </filter>\n
    \   <encoder>\n      <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{1024}
    - %msg%n\n      </pattern>\n    </encoder>\n  </appender>\n\n  <appender name=\"INFO\"
    class=\"ch.qos.logback.core.ConsoleAppender\">\n    <filter class=\"ch.qos.logback.classic.filter.LevelFilter\">\n
    \     <level>INFO</level>\n      <onMatch>ACCEPT</onMatch>\n      <onMismatch>DENY</onMismatch>\n
    \   </filter>\n  </appender>\n\n  <appender name=\"DEBUG\" class=\"ch.qos.logback.core.ConsoleAppender\">\n\n
    \   <encoder>\n      <pattern>\"%d [%thread] %-5level %logger{1024} - %msg%n\"</pattern>\n
    \   </encoder>\n  </appender>\n\n  <appender name=\"ERROR\" class=\"ch.qos.logback.core.ConsoleAppender\">
    class=\"ch.qos.logback.core.ConsoleAppender\">\n    <filter class=\"ch.qos.logback.classic.filter.LevelFilter\">\n
    \     <level>ERROR</level>\n      <onMatch>ACCEPT</onMatch>\n      <onMismatch>DENY</onMismatch>\n
    \   </filter>\n    <encoder>\n      <pattern>\"%d [%thread] %-5level %logger{1024}
    - %msg%n\"</pattern>\n    </encoder>\n  </appender>\n\n\n  <!-- Msgrtr related
    loggers -->\n  <logger name=\"org.onap.dmaap.dmf.mr.service\" level=\"INFO\" />\n
    \ <logger name=\"org.onap.dmaap.dmf.mr.service.impl\" level=\"INFO\" />\n\n  <logger
    name=\"org.onap.dmaap.dmf.mr.resources\" level=\"INFO\" />\n  <logger name=\"org.onap.dmaap.dmf.mr.resources.streamReaders\"
    level=\"INFO\" />\n\n  <logger name=\"org.onap.dmaap.dmf.mr.backends\" level=\"INFO\"
    />\n  <logger name=\"org.onap.dmaap.dmf.mr.backends.kafka\" level=\"INFO\" />\n
    \ <logger name=\"org.onap.dmaap.dmf.mr.backends.memory\" level=\"INFO\" />\n\n
    \ <logger name=\"org.onap.dmaap.dmf.mr.beans\" level=\"INFO\" />\n\n  <logger
    name=\"org.onap.dmaap.dmf.mr.constants\" level=\"INFO\" />\n\n  <logger name=\"org.onap.dmaap.dmf.mr.exception\"
    level=\"INFO\" />\n\n  <logger name=\"org.onap.dmaap.dmf.mr.listener\" level=\"INFO\"
    />\n\n  <logger name=\"org.onap.dmaap.dmf.mr.metabroker\" level=\"INFO\" />\n\n
    \ <logger name=\"org.onap.dmaap.dmf.mr.metrics.publisher\" level=\"INFO\" />\n
    \ <logger name=\"org.onap.dmaap.dmf.mr.metrics.publisher.impl\" level=\"INFO\"
    />\n\n\n\n  <logger name=\"org.onap.dmaap.dmf.mr.security\" level=\"INFO\" />\n
    \ <logger name=\"org.onap.dmaap.dmf.mr.security.impl\" level=\"INFO\" />\n\n  <logger
    name=\"org.onap.dmaap.dmf.mr.transaction\" level=\"INFO\" />\n  <logger name=\"com.att.dmf.mr.transaction.impl\"
    level=\"INFO\" />\n\n  <logger name=\"org.onap.dmaap.dmf.mr.metabroker\" level=\"INFO\"
    />\n  <logger name=\"org.onap.dmaap.dmf.mr.metabroker\" level=\"INFO\" />\n\n
    \ <logger name=\"org.onap.dmaap.dmf.mr.utils\" level=\"INFO\" />\n  <logger name=\"org.onap.dmaap.mr.filter\"
    level=\"INFO\" />\n\n  <!--<logger name=\"com.att.nsa.cambria.*\" level=\"INFO\"
    />-->\n\n  <!-- Msgrtr loggers in ajsc -->\n  <logger name=\"org.onap.dmaap.service\"
    level=\"INFO\" />\n  <logger name=\"org.onap.dmaap\" level=\"INFO\" />\n\n\n  <!--
    Spring related loggers -->\n  <logger name=\"org.springframework\" level=\"WARN\"
    additivity=\"false\"/>\n  <logger name=\"org.springframework.beans\" level=\"WARN\"
    additivity=\"false\"/>\n  <logger name=\"org.springframework.web\" level=\"WARN\"
    additivity=\"false\" />\n  <logger name=\"com.blog.spring.jms\" level=\"WARN\"
    additivity=\"false\" />\n\n  <!-- AJSC Services (bootstrap services) -->\n  <logger
    name=\"ajsc\" level=\"WARN\" additivity=\"false\"/>\n  <logger name=\"ajsc.RouteMgmtService\"
    level=\"INFO\" additivity=\"false\"/>\n  <logger name=\"ajsc.ComputeService\"
    level=\"INFO\" additivity=\"false\" />\n  <logger name=\"ajsc.VandelayService\"
    level=\"WARN\" additivity=\"false\"/>\n  <logger name=\"ajsc.FilePersistenceService\"
    level=\"WARN\" additivity=\"false\"/>\n  <logger name=\"ajsc.UserDefinedJarService\"
    level=\"WARN\" additivity=\"false\" />\n  <logger name=\"ajsc.UserDefinedBeansDefService\"
    level=\"WARN\" additivity=\"false\" />\n  <logger name=\"ajsc.LoggingConfigurationService\"
    level=\"WARN\" additivity=\"false\" />\n\n  <!-- AJSC related loggers (DME2 Registration,
    csi logging, restlet, servlet\n    logging) -->\n  <logger name=\"ajsc.utils\"
    level=\"WARN\" additivity=\"false\"/>\n  <logger name=\"ajsc.utils.DME2Helper\"
    level=\"INFO\" additivity=\"false\" />\n  <logger name=\"ajsc.filters\" level=\"DEBUG\"
    additivity=\"false\" />\n  <logger name=\"ajsc.beans.interceptors\" level=\"DEBUG\"
    additivity=\"false\" />\n  <logger name=\"ajsc.restlet\" level=\"DEBUG\" additivity=\"false\"
    />\n  <logger name=\"ajsc.servlet\" level=\"DEBUG\" additivity=\"false\" />\n
    \ <logger name=\"com.att\" level=\"WARN\" additivity=\"false\" />\n  <logger name=\"com.att.ajsc.csi.logging\"
    level=\"WARN\" additivity=\"false\" />\n  <logger name=\"com.att.ajsc.filemonitor\"
    level=\"WARN\" additivity=\"false\"/>\n\n  <logger name=\"com.att.nsa.dmaap.util\"
    level=\"INFO\" additivity=\"false\"/>\n  <logger name=\"com.att.cadi.filter\"
    level=\"INFO\" additivity=\"false\" />\n\n\n  <!-- Other Loggers that may help
    troubleshoot -->\n  <logger name=\"net.sf\" level=\"WARN\" additivity=\"false\"
    />\n  <logger name=\"org.apache.commons.httpclient\" level=\"WARN\" additivity=\"false\"/>\n
    \ <logger name=\"org.apache.commons\" level=\"WARN\" additivity=\"false\" />\n
    \ <logger name=\"org.apache.coyote\" level=\"WARN\" additivity=\"false\"/>\n  <logger
    name=\"org.apache.jasper\" level=\"WARN\" additivity=\"false\"/>\n\n  <!-- Camel
    Related Loggers (including restlet/servlet/jaxrs/cxf logging.\n    May aid in
    troubleshooting) -->\n  <logger name=\"org.apache.camel\" level=\"WARN\" additivity=\"false\"
    />\n  <logger name=\"org.apache.cxf\" level=\"WARN\" additivity=\"false\" />\n
    \ <logger name=\"org.apache.camel.processor.interceptor\" level=\"WARN\" additivity=\"false\"/>\n
    \ <logger name=\"org.apache.cxf.jaxrs.interceptor\" level=\"WARN\" additivity=\"false\"
    />\n  <logger name=\"org.apache.cxf.service\" level=\"WARN\" additivity=\"false\"
    />\n  <logger name=\"org.restlet\" level=\"DEBUG\" additivity=\"false\" />\n  <logger
    name=\"org.apache.camel.component.restlet\" level=\"DEBUG\" additivity=\"false\"
    />\n  <logger name=\"org.apache.kafka\" level=\"DEBUG\" additivity=\"false\" />\n
    \ <logger name=\"org.apache.zookeeper\" level=\"INFO\" additivity=\"false\" />\n
    \ <logger name=\"org.I0Itec.zkclient\" level=\"DEBUG\" additivity=\"false\" />\n\n
    \ <!-- logback internals logging -->\n  <logger name=\"ch.qos.logback.classic\"
    level=\"INFO\" additivity=\"false\"/>\n  <logger name=\"ch.qos.logback.core\"
    level=\"INFO\" additivity=\"false\" />\n\n  <!-- logback jms appenders & loggers
    definition starts here -->\n  <!-- logback jms appenders & loggers definition
    starts here -->\n  <appender name=\"auditLogs\" class=\"ch.qos.logback.core.ConsoleAppender\">\n
    \   <filter class=\"ch.qos.logback.classic.filter.ThresholdFilter\">\n    </filter>\n
    \   <encoder>\n      <pattern>\"%d [%thread] %-5level %logger{1024} - %msg%n\"</pattern>\n
    \   </encoder>\n  </appender>\n  <appender name=\"perfLogs\" class=\"ch.qos.logback.core.ConsoleAppender\">\n
    \   <filter class=\"ch.qos.logback.classic.filter.ThresholdFilter\">\n    </filter>\n
    \   <encoder>\n      <pattern>\"%d [%thread] %-5level %logger{1024} - %msg%n\"</pattern>\n
    \   </encoder>\n  </appender>\n  <appender name=\"ASYNC-audit\" class=\"ch.qos.logback.classic.AsyncAppender\">\n
    \   <queueSize>1000</queueSize>\n    <discardingThreshold>0</discardingThreshold>\n
    \   <appender-ref ref=\"Audit-Record-Queue\" />\n  </appender>\n\n  <logger name=\"AuditRecord\"
    level=\"INFO\" additivity=\"FALSE\">\n    <appender-ref ref=\"STDOUT\" />\n  </logger>\n
    \ <logger name=\"AuditRecord_DirectCall\" level=\"INFO\" additivity=\"FALSE\">\n
    \   <appender-ref ref=\"STDOUT\" />\n  </logger>\n  <appender name=\"ASYNC-perf\"
    class=\"ch.qos.logback.classic.AsyncAppender\">\n    <queueSize>1000</queueSize>\n
    \   <discardingThreshold>0</discardingThreshold>\n    <appender-ref ref=\"Performance-Tracker-Queue\"
    />\n  </appender>\n  <logger name=\"PerfTrackerRecord\" level=\"INFO\" additivity=\"FALSE\">\n
    \   <appender-ref ref=\"ASYNC-perf\" />\n    <appender-ref ref=\"perfLogs\" />\n
    \ </logger>\n  <!-- logback jms appenders & loggers definition ends here -->\n\n
    \ <root level=\"DEBUG\">\n    <appender-ref ref=\"DEBUG\" />\n    <appender-ref
    ref=\"ERROR\" />\n    <appender-ref ref=\"INFO\" />\n    <appender-ref ref=\"STDOUT\"
    />\n  </root>\n\n</configuration> \n"
kind: ConfigMap
metadata:
  name: mr-log
  namespace: smo