apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
  namespace: smo
spec:
  clusterIP: 10.96.0.91
  clusterIPs:
  - 10.96.0.91
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "2181"
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    io.kompose.service: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}