apiVersion: v1
kind: Service
metadata:
  labels:
    app: vescollector
  name: vescollector
  namespace: smo
spec:
  clusterIP: 10.96.0.194
  clusterIPs:
  - 10.96.0.194
  externalIPs:
  - 192.168.122.87
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vescollector
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}