apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-7.3.5
  name: mariadb-galera-headless
  namespace: smo
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: galera
    port: 4567
    protocol: TCP
    targetPort: galera
  - name: ist
    port: 4568
    protocol: TCP
    targetPort: ist
  - name: sst
    port: 4444
    protocol: TCP
    targetPort: sst
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: mariadb-galera
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}