apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-7.3.5
  name: mariadb-galera
  namespace: smo
spec:
  clusterIP: 10.96.0.239
  clusterIPs:
  - 10.96.0.239
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: mariadb-galera
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}